from pathlib import Path


# Estabelece a pasta que contem as figuras e sons.
IMG_DIR = Path(__file__).parent.parent / 'img'

# Dados gerais do jogo.
TITULO = 'Exemplo de Tiles'
WIDTH = 480 # Largura da tela
HEIGHT = 600 # Altura da tela
TILE_SIZE = 40 # Tamanho de cada tile (cada tile é um quadrado)

# Define algumas variáveis com as cores básicas
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

# Define os tipos de tiles
GRASS = 0
SAND1 = 1
SAND2 = 2
SAND3 = 3
SAND4 = 4
SAND5 = 5
SAND6 = 6
SAND7 = 7
SAND8 = 8
WATER = 9

# Define o mapa com os tipos de tiles
MAP = [
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
    [GRASS, SAND1, SAND2, SAND2, SAND3, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
    [GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
    [GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
    [GRASS, SAND4, WATER, WATER, SAND5, GRASS, SAND1, SAND2, SAND2, SAND3, GRASS, GRASS],
    [GRASS, SAND4, WATER, WATER, SAND5, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, SAND6, SAND7, SAND7, SAND8, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND4, WATER, WATER, SAND5, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, SAND6, SAND7, SAND7, SAND8, GRASS, GRASS],
    [GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
]

# Define estados possíveis do jogador
STILL = 0
JUMPING = 1
FALLING = 2
